/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar histórico y trazabilidad
         * @description CU-05. Busca notificaciones por filtros combinables. Cada resultado incluye su recorrido completo de intentos, no solo el estado actual (a diferencia de GET /notifications/{id}).
         */
        get: operations["searchNotifications"];
        put?: never;
        /**
         * Enviar una notificación
         * @description CU-01. Acepta la notificación, la registra en estado PENDING y la encola para su despacho asíncrono. Si ya existe una notificación con el mismo (tenantId, externalId), devuelve esa misma notificación en vez de crear una segunda (idempotencia).
         */
        post: operations["sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications:subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suscribirse a actualizaciones en tiempo real
         * @description Historia "dashboard en tiempo real". Abre un stream Server-Sent Events: primero reproduce la foto vigente de las notificaciones del tenant que cumplen los filtros (equivalente a repetir GET /notifications sin paginar, acotado a 200 resultados), y luego continúa entregando cada cambio relevante mientras la conexión permanezca abierta. Una reconexión (ej. tras una caída de red) es, para el servidor, una solicitud nueva -- siempre reproduce la foto vigente antes de retomar el flujo en vivo, sin necesitar ningún encabezado ni parámetro de reanudación.
         */
        get: operations["subscribeToNotificationUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications:sendBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar un lote de notificaciones
         * @description CU-02. El lote es su propia unidad de seguimiento (RF-02), no un bucle sobre POST /notifications -- cada elemento se valida e idempotiza por separado, y un elemento inválido no bloquea a los demás.
         */
        post: operations["sendNotificationBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar el estado de una notificación
         * @description CU-04. Devuelve el estado actual, canal, proveedor y marca de tiempo del último intento.
         */
        get: operations["getNotificationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reintentar el envío manualmente
         * @description CU-06. Solo válido si el estado actual es FAILED o RECOVERABLE. Reencola la notificación y registra el reintento como manual (distinto del automático) para efectos de auditoría.
         */
        post: operations["retryNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar los canales del catálogo y cómo se enrutan
         * @description CU-07 (lectura). Devuelve los canales que el enrutamiento está usando en este momento, cada uno con sus proveedores en orden de preferencia y el estado de cada proveedor. Hoy el despacho usa solo el proveedor en la posición 1; los demás se listan en su orden pero no se usan como respaldo automático. El catálogo es del despliegue, no del tenant: la respuesta es la misma para cualquier X-Tenant-Id. Un cambio guardado en el catálogo aparece aquí en el mismo refresco en que el enrutamiento empieza a usarlo. Ningún campo contiene el valor de una credencial.
         */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar los proveedores, su estado y dónde se usan
         * @description CU-08 (lectura). Devuelve la unión de los proveedores con adaptador en este despliegue y los que nombra el catálogo, cada uno con su estado y los canales en que aparece. MISSING_ADAPTER indica que el catálogo nombra un proveedor para el que el despliegue no tiene adaptador. El estado de habilitación es el de configuración de la réplica que responde, no la salud actual del proveedor. Misma respuesta para cualquier X-Tenant-Id; ningún campo contiene el valor de una credencial.
         */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels:register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar o actualizar un canal
         * @description CU-07. Requiere permiso de ADMINISTRADOR. Da de alta el canal en el catálogo, sin desplegar código (RF-19). Si el canal ya existe, esta misma operación lo actualiza. Bloqueado: el catálogo dinámico ya existe, pero su escritura por API aún no está habilitada.
         */
        post: operations["registerChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers:register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un proveedor para uno o más canales
         * @description CU-08. Requiere permiso de ADMINISTRADOR y que el adaptador del proveedor ya exista en el código (no puede registrarse un providerId sin adaptador). Si falta una credencial requerida, el proveedor queda registrado pero deshabilitado -- nunca a medias en silencio. Bloqueado hasta que exista el catálogo dinámico (Fase 6).
         */
        post: operations["registerProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipientId}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar las preferencias de un destinatario
         * @description CU-09. Lectura antes de escribir -- el actor consulta lo vigente antes de modificarlo.
         */
        get: operations["getRecipientPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipientId}:updatePreferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Actualizar las preferencias de un destinatario
         * @description CU-09. Declara por qué canales acepta ser contactado, o solicita su baja total (optedOutAll). Una baja total hace que CU-03 descarte (DISCARDED) sus notificaciones futuras en vez de intentarlas.
         */
        post: operations["updateRecipientPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendNotificationRequest: {
            /**
             * @description Identificador propio del sistema cliente, usado para idempotencia.
             * @example order-42
             */
            externalId: string;
            /**
             * @description Canal registrado en el catálogo. La configuración por defecto declara EMAIL, SMS y PUSH.
             * @example EMAIL
             */
            channelType: string;
            /**
             * @description Identificador del destinatario, estable entre canales.
             * @example recipient-1
             */
            recipientId: string;
            /**
             * @description Dirección concreta del canal usado en este envío (email, teléfono, etc.). En SMS es un número en formato internacional (signo +, código de país y número, ej. +573001234567); un número sin ese formato termina en FAILED sin enviarse. En PUSH es el identificador de dispositivo que el proveedor de push emitió a la aplicación cliente (ej. device-token-demo-1234); se trata como texto opaco y no se valida su forma: un identificador inválido o caducado termina en FAILED sin reintentos.
             * @example alice@example.com
             */
            recipientAddress: string;
            /**
             * @description Opcional -- algunos canales (ej. SMS) no lo usan. En SMS se admite y se ignora: no se envía ni se antepone al cuerpo. En PUSH es el título visible, opcional, de hasta 100 caracteres.
             * @example Bienvenida
             */
            subject?: string | null;
            /**
             * @description Cuerpo de la notificación. La longitud máxima la fija la forma de contenido del canal en el catálogo; en SMS son 160 caracteres y en PUSH 900 por defecto. Un contenido más largo se rechaza con 400 y nunca se trunca.
             * @example Hola Alice, tu pedido fue confirmado.
             */
            body: string;
            priority: components["schemas"]["Priority"];
        };
        SendNotificationResponse: {
            /** Format: uuid */
            notificationId?: string;
            status?: components["schemas"]["NotificationStatus"];
            /** @description true si ya existía una notificación con el mismo (tenantId, externalId). */
            duplicate?: boolean;
        };
        SendNotificationBatchRequest: {
            /** @description Opcional -- si no se envía, el componente genera uno. */
            batchId?: string | null;
            items: components["schemas"]["SendNotificationRequest"][];
        };
        BatchAcceptedResponse: {
            batchId?: string;
            results?: components["schemas"]["BatchItemResult"][];
        };
        BatchItemResult: {
            externalId?: string;
            /** @enum {string} */
            outcome?: "ACCEPTED" | "DUPLICATE" | "REJECTED";
            /**
             * Format: uuid
             * @description Nulo cuando outcome es REJECTED.
             */
            notificationId?: string | null;
            /** @description Solo presente cuando outcome es REJECTED. */
            rejectionReason?: string | null;
        };
        NotificationStatusResponse: {
            /** Format: uuid */
            notificationId?: string;
            status?: components["schemas"]["NotificationStatus"];
            channelType?: string;
            /** @description Proveedor del último intento de envío. Nulo si aún no se ha intentado despachar. */
            providerId?: string | null;
            /** Format: date-time */
            lastUpdatedAt?: string;
        };
        NotificationSearchResponse: {
            items: components["schemas"]["NotificationHistoryItem"][];
            /** @description Tamaño de página efectivamente aplicado. */
            limit: number;
            /** @description Offset efectivamente aplicado. */
            offset: number;
            /** @description true si existen más resultados después de esta página. */
            hasNext: boolean;
        };
        NotificationHistoryItem: {
            /** Format: uuid */
            notificationId?: string;
            externalId?: string;
            recipientId?: string;
            channelType?: string;
            status?: components["schemas"]["NotificationStatus"];
            /** Format: date-time */
            acceptedAt?: string;
            deliveryAttempts?: components["schemas"]["DeliveryAttempt"][];
        };
        DeliveryAttempt: {
            /** Format: date-time */
            occurredOn?: string;
            /** @enum {string} */
            result?: "ACCEPTED" | "RECOVERABLE_FAILURE" | "PERMANENT_FAILURE";
            /** @enum {string} */
            origin?: "MANUAL" | "AUTOMATIC";
            providerId?: string;
        };
        RegisterChannelRequest: {
            /** @example SMS */
            channelType: string;
            /** @description Esquema JSON Schema (como string) contra el que se valida el contenido enviado por este canal. */
            contentSchema?: string | null;
            /** @description Tope de reintentos automáticos para este canal. Nulo usa el default global. */
            maxRetryAttempts?: number | null;
        };
        RegisterProviderRequest: {
            /** @example brevo */
            providerId: string;
            channels: {
                channelType: string;
                /** @description Orden de preferencia dentro del canal (1 = preferente). */
                preferenceOrder: number;
            }[];
        };
        RegisterProviderResponse: {
            providerId?: string;
            /** @description false si falta alguna credencial requerida por este proveedor. */
            enabled?: boolean;
            /** @description Vacío cuando enabled es true. */
            missingCredentials?: string[];
        };
        RecipientPreferencesResponse: {
            recipientId?: string;
            optedOutAll?: boolean;
            /** @description Ignorado si optedOutAll es true. */
            acceptedChannels?: string[];
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdatePreferencesRequest: {
            /** @default false */
            optedOutAll: boolean;
            /** @description Ignorado si optedOutAll es true. */
            acceptedChannels?: string[];
        };
        /**
         * @description ENABLED: tiene adaptador y su configuración está completa. DISABLED: tiene adaptador pero le falta o tiene mal formada una credencial (ver statusReason). MISSING_ADAPTER: el catálogo lo nombra pero el despliegue no tiene adaptador para él.
         * @enum {string}
         */
        ProviderStatus: "ENABLED" | "DISABLED" | "MISSING_ADAPTER";
        ChannelCatalogResponse: {
            items: components["schemas"]["ChannelItem"][];
        };
        ChannelItem: {
            /** @example EMAIL */
            channelType: string;
            /** @description Forma de contenido (JSON Schema como texto) tal como está guardada. Nulo si el canal no declara ninguna. */
            contentSchema: string | null;
            /** @description En orden de preferencia. */
            providers: components["schemas"]["ChannelProviderItem"][];
        };
        ChannelProviderItem: {
            /** @example simulated */
            providerId: string;
            /** @description 1 = preferente, el único que usa hoy el despacho. */
            preferenceOrder: number;
            status: components["schemas"]["ProviderStatus"];
            /**
             * @description Nulo cuando status es ENABLED. Nombra la configuración ausente o mal formada, nunca su valor.
             * @example missing notification.provider.twilio.account-sid (TWILIO_ACCOUNT_SID)
             */
            statusReason: string | null;
        };
        ProviderCatalogResponse: {
            items: components["schemas"]["ProviderItem"][];
        };
        ProviderItem: {
            /** @example twilio */
            providerId: string;
            status: components["schemas"]["ProviderStatus"];
            /** @description Nulo cuando status es ENABLED. Nombra la configuración ausente o mal formada, nunca su valor. */
            statusReason: string | null;
            /** @description Canales que nombran a este proveedor, con su posición en cada uno. Vacío si ninguno. */
            channels: {
                channelType: string;
                preferenceOrder: number;
            }[];
        };
        ErrorResponse: {
            message?: string;
        };
        /** @enum {string} */
        Priority: "LOW" | "NORMAL" | "HIGH";
        /** @enum {string} */
        NotificationStatus: "PENDING" | "IN_PROCESS" | "DELIVERED" | "RECOVERABLE" | "FAILED" | "DISCARDED";
        NotificationLiveUpdate: {
            /**
             * @description UPSERT: la notificación cumple los filtros activos, el dashboard debe mostrarla/actualizarla. REMOVE: dejó de cumplirlos, el dashboard debe quitarla de la vista visible.
             * @enum {string}
             */
            action: "UPSERT" | "REMOVE";
            notification: components["schemas"]["NotificationHistoryItem"];
        };
    };
    responses: never;
    parameters: {
        /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
        TenantId: string;
        /** @description Identificador de la notificación. */
        NotificationId: string;
        /** @description Identificador del destinatario, estable entre canales. */
        RecipientId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchNotifications: {
        parameters: {
            query?: {
                recipientId?: string;
                channelType?: string;
                status?: components["schemas"]["NotificationStatus"];
                /** @description Fecha/hora mínima de aceptación (inclusive). */
                from?: string;
                /** @description Fecha/hora máxima de aceptación (inclusive). */
                to?: string;
                /** @description Tamaño de página. Default 50, máximo 200. */
                limit?: number;
                /** @description Posición inicial dentro del conjunto de resultados. Default 0. */
                offset?: number;
            };
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de notificaciones que cumplen el criterio (items vacío si no hay resultados). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSearchResponse"];
                };
            };
            /** @description Parámetros inválidos -- from posterior a to, o limit/offset fuera de su rango válido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendNotification: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description Notificación aceptada (nueva o duplicada -- ver el campo "duplicate"). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendNotificationResponse"];
                };
            };
            /** @description El canal no existe/está deshabilitado, o el contenido no cumple el esquema del canal. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    subscribeToNotificationUpdates: {
        parameters: {
            query?: {
                recipientId?: string;
                channelType?: string;
                status?: components["schemas"]["NotificationStatus"];
                /** @description Fecha/hora mínima de aceptación (inclusive). Mismo campo que en la búsqueda. */
                from?: string;
                /** @description Fecha/hora máxima de aceptación (inclusive). Mismo campo que en la búsqueda. */
                to?: string;
            };
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Server-Sent Events. Cada evento `data` es un `NotificationLiveUpdate`. La conexión permanece abierta hasta que el cliente la cierra; el servidor intercala comentarios de keep-alive periódicos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["NotificationLiveUpdate"];
                };
            };
        };
    };
    sendNotificationBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationBatchRequest"];
            };
        };
        responses: {
            /** @description Lote aceptado -- ver el resultado individual de cada elemento. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAcceptedResponse"];
                };
            };
        };
    };
    getNotificationStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador de la notificación. */
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado actual de la notificación. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationStatusResponse"];
                };
            };
            /** @description No existe una notificación con ese id, o no pertenece al tenant del solicitante -- ambos casos responden igual, para no revelar si el id existe bajo otro cliente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retryNotification: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador de la notificación. */
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reintento aceptado, la notificación vuelve al flujo de despacho. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationStatusResponse"];
                };
            };
            /** @description El estado actual no admite reintento (ej. ya está DELIVERED). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una notificación con ese id para este tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canales ordenados por channelType (items vacío si el catálogo está vacío). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelCatalogResponse"];
                };
            };
            /** @description Falta el X-Tenant-Id o está vacío. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proveedores ordenados por providerId. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCatalogResponse"];
                };
            };
            /** @description Falta el X-Tenant-Id o está vacío. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterChannelRequest"];
            };
        };
        responses: {
            /** @description Canal registrado o actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El esquema de validación del canal está mal formado. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerProvider: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterProviderRequest"];
            };
        };
        responses: {
            /** @description Proveedor registrado -- ver el campo "enabled" si faltó alguna credencial. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterProviderResponse"];
                };
            };
            /** @description No existe un adaptador de código para ese providerId. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecipientPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador del destinatario, estable entre canales. */
                recipientId: components["parameters"]["RecipientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferencias vigentes (por defecto, todos los canales aceptados). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientPreferencesResponse"];
                };
            };
        };
    };
    updateRecipientPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador del destinatario, estable entre canales. */
                recipientId: components["parameters"]["RecipientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description Preferencias actualizadas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientPreferencesResponse"];
                };
            };
        };
    };
}
