/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar histórico y trazabilidad
         * @description CU-05. Busca notificaciones por filtros combinables. Cada resultado incluye su recorrido completo de intentos, no solo el estado actual (a diferencia de GET /notifications/{id}).
         */
        get: operations["searchNotifications"];
        put?: never;
        /**
         * Enviar una notificación
         * @description CU-01. Acepta la notificación, la registra en estado PENDING y la encola para su despacho asíncrono. Si ya existe una notificación con el mismo (tenantId, externalId), devuelve esa misma notificación en vez de crear una segunda (idempotencia).
         */
        post: operations["sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications:sendBatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar un lote de notificaciones
         * @description CU-02. El lote es su propia unidad de seguimiento (RF-02), no un bucle sobre POST /notifications -- cada elemento se valida e idempotiza por separado, y un elemento inválido no bloquea a los demás.
         */
        post: operations["sendNotificationBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar el estado de una notificación
         * @description CU-04. Devuelve el estado actual, canal, proveedor y marca de tiempo del último intento.
         */
        get: operations["getNotificationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reintentar el envío manualmente
         * @description CU-06. Solo válido si el estado actual es FAILED o RECOVERABLE. Reencola la notificación y registra el reintento como manual (distinto del automático) para efectos de auditoría.
         */
        post: operations["retryNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels:register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar o actualizar un canal
         * @description CU-07. Requiere permiso de ADMINISTRADOR. Da de alta el canal en el catálogo, sin desplegar código (RF-19). Si el canal ya existe, esta misma operación lo actualiza. Bloqueado hasta que exista el catálogo dinámico (Fase 6) -- hoy el catálogo es estático en application.yml.
         */
        post: operations["registerChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers:register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un proveedor para uno o más canales
         * @description CU-08. Requiere permiso de ADMINISTRADOR y que el adaptador del proveedor ya exista en el código (no puede registrarse un providerId sin adaptador). Si falta una credencial requerida, el proveedor queda registrado pero deshabilitado -- nunca a medias en silencio. Bloqueado hasta que exista el catálogo dinámico (Fase 6).
         */
        post: operations["registerProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipientId}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar las preferencias de un destinatario
         * @description CU-09. Lectura antes de escribir -- el actor consulta lo vigente antes de modificarlo.
         */
        get: operations["getRecipientPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipientId}:updatePreferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Actualizar las preferencias de un destinatario
         * @description CU-09. Declara por qué canales acepta ser contactado, o solicita su baja total (optedOutAll). Una baja total hace que CU-03 descarte (DISCARDED) sus notificaciones futuras en vez de intentarlas.
         */
        post: operations["updateRecipientPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SendNotificationRequest: {
            /**
             * @description Identificador propio del sistema cliente, usado para idempotencia.
             * @example order-42
             */
            externalId: string;
            /**
             * @description Canal registrado en el catálogo (hoy solo EMAIL está configurado).
             * @example EMAIL
             */
            channelType: string;
            /**
             * @description Identificador del destinatario, estable entre canales.
             * @example recipient-1
             */
            recipientId: string;
            /**
             * @description Dirección concreta del canal usado en este envío (email, teléfono, etc.).
             * @example alice@example.com
             */
            recipientAddress: string;
            /**
             * @description Opcional -- algunos canales (ej. SMS) no lo usan.
             * @example Bienvenida
             */
            subject?: string | null;
            /** @example Hola Alice, tu pedido fue confirmado. */
            body: string;
            priority: components["schemas"]["Priority"];
        };
        SendNotificationResponse: {
            /** Format: uuid */
            notificationId?: string;
            status?: components["schemas"]["NotificationStatus"];
            /** @description true si ya existía una notificación con el mismo (tenantId, externalId). */
            duplicate?: boolean;
        };
        SendNotificationBatchRequest: {
            /** @description Opcional -- si no se envía, el componente genera uno. */
            batchId?: string | null;
            items: components["schemas"]["SendNotificationRequest"][];
        };
        BatchAcceptedResponse: {
            batchId?: string;
            results?: components["schemas"]["BatchItemResult"][];
        };
        BatchItemResult: {
            externalId?: string;
            /** @enum {string} */
            outcome?: "ACCEPTED" | "DUPLICATE" | "REJECTED";
            /**
             * Format: uuid
             * @description Nulo cuando outcome es REJECTED.
             */
            notificationId?: string | null;
            /** @description Solo presente cuando outcome es REJECTED. */
            rejectionReason?: string | null;
        };
        NotificationStatusResponse: {
            /** Format: uuid */
            notificationId?: string;
            status?: components["schemas"]["NotificationStatus"];
            channelType?: string;
            /** @description Proveedor del último intento de envío. Nulo si aún no se ha intentado despachar. */
            providerId?: string | null;
            /** Format: date-time */
            lastUpdatedAt?: string;
        };
        NotificationHistoryItem: {
            /** Format: uuid */
            notificationId?: string;
            externalId?: string;
            recipientId?: string;
            channelType?: string;
            status?: components["schemas"]["NotificationStatus"];
            /** Format: date-time */
            acceptedAt?: string;
            deliveryAttempts?: components["schemas"]["DeliveryAttempt"][];
        };
        DeliveryAttempt: {
            /** Format: date-time */
            occurredOn?: string;
            /** @enum {string} */
            result?: "ACCEPTED" | "RECOVERABLE_FAILURE" | "PERMANENT_FAILURE";
            /** @enum {string} */
            origin?: "MANUAL" | "AUTOMATIC";
            providerId?: string;
        };
        RegisterChannelRequest: {
            /** @example SMS */
            channelType: string;
            /** @description Esquema JSON Schema (como string) contra el que se valida el contenido enviado por este canal. */
            contentSchema?: string | null;
            /** @description Tope de reintentos automáticos para este canal. Nulo usa el default global. */
            maxRetryAttempts?: number | null;
        };
        RegisterProviderRequest: {
            /** @example brevo */
            providerId: string;
            channels: {
                channelType: string;
                /** @description Orden de preferencia dentro del canal (1 = preferente). */
                preferenceOrder: number;
            }[];
        };
        RegisterProviderResponse: {
            providerId?: string;
            /** @description false si falta alguna credencial requerida por este proveedor. */
            enabled?: boolean;
            /** @description Vacío cuando enabled es true. */
            missingCredentials?: string[];
        };
        RecipientPreferencesResponse: {
            recipientId?: string;
            optedOutAll?: boolean;
            /** @description Ignorado si optedOutAll es true. */
            acceptedChannels?: string[];
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdatePreferencesRequest: {
            /** @default false */
            optedOutAll: boolean;
            /** @description Ignorado si optedOutAll es true. */
            acceptedChannels?: string[];
        };
        ErrorResponse: {
            message?: string;
        };
        /** @enum {string} */
        Priority: "LOW" | "NORMAL" | "HIGH";
        /** @enum {string} */
        NotificationStatus: "PENDING" | "IN_PROCESS" | "DELIVERED" | "RECOVERABLE" | "FAILED" | "DISCARDED";
    };
    responses: never;
    parameters: {
        /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
        TenantId: string;
        /** @description Identificador de la notificación. */
        NotificationId: string;
        /** @description Identificador del destinatario, estable entre canales. */
        RecipientId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchNotifications: {
        parameters: {
            query?: {
                recipientId?: string;
                channelType?: string;
                status?: components["schemas"]["NotificationStatus"];
                /** @description Fecha/hora mínima de aceptación (inclusive). */
                from?: string;
                /** @description Fecha/hora máxima de aceptación (inclusive). */
                to?: string;
            };
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de notificaciones que cumplen el criterio (vacía si no hay resultados). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationHistoryItem"][];
                };
            };
        };
    };
    sendNotification: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description Notificación aceptada (nueva o duplicada -- ver el campo "duplicate"). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendNotificationResponse"];
                };
            };
            /** @description El canal no existe/está deshabilitado, o el contenido no cumple el esquema del canal. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendNotificationBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationBatchRequest"];
            };
        };
        responses: {
            /** @description Lote aceptado -- ver el resultado individual de cada elemento. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAcceptedResponse"];
                };
            };
        };
    };
    getNotificationStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador de la notificación. */
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado actual de la notificación. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationStatusResponse"];
                };
            };
            /** @description No existe una notificación con ese id, o no pertenece al tenant del solicitante -- ambos casos responden igual, para no revelar si el id existe bajo otro cliente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retryNotification: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador de la notificación. */
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reintento aceptado, la notificación vuelve al flujo de despacho. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationStatusResponse"];
                };
            };
            /** @description El estado actual no admite reintento (ej. ya está DELIVERED). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una notificación con ese id para este tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterChannelRequest"];
            };
        };
        responses: {
            /** @description Canal registrado o actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El esquema de validación del canal está mal formado. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerProvider: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterProviderRequest"];
            };
        };
        responses: {
            /** @description Proveedor registrado -- ver el campo "enabled" si faltó alguna credencial. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterProviderResponse"];
                };
            };
            /** @description No existe un adaptador de código para ese providerId. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecipientPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador del destinatario, estable entre canales. */
                recipientId: components["parameters"]["RecipientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferencias vigentes (por defecto, todos los canales aceptados). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientPreferencesResponse"];
                };
            };
        };
    };
    updateRecipientPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador del tenant solicitante. Placeholder mientras CU-10 (autenticación) sigue bloqueado por DEP-01 -- se reemplazará por la identidad resuelta desde el token una vez se cierre esa dependencia con el equipo de Seguridad. */
                "X-Tenant-Id": components["parameters"]["TenantId"];
            };
            path: {
                /** @description Identificador del destinatario, estable entre canales. */
                recipientId: components["parameters"]["RecipientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description Preferencias actualizadas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientPreferencesResponse"];
                };
            };
        };
    };
}
